### PR TITLE
add th18 trial support

### PR DESCRIPTION
**Pull request by relick**
Adds v0.01b of th18. Code is more or less the same as th17, excluding the features disabled in the demo. There are so many ability cards I'm not sure it's worth trying to detect them (and I haven't had much luck trying to find them in memory in any case).

### CODE REVIEW

**Comment by relick** [comment]
Actually hold on merging, the midboss detection stopped working after I ran the game a few more times....

**Comment by relick** [comment]
Okay, it's all good now :)

**Comment by TheBakaRem** [comment]
After a bit of testing with v0.02a, it looks like the memory adresses changed completely compared to v0.01b. I'll do some testing in order to find and use the new memory adresses.

**Comment by TheBakaRem** [comment]
I modified the adresses for v0.02a, tested it and it now works properly. I can merge this now. Thanks for the contribution!

**Pull request merged**
